modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://ruasolcorporation.com"

[[mods]]
modId="ruasolmarket"
version="4.0.5"
displayName="Ruasol Market"
authors="Ruasol's Tavern"
description='''
Ruasol's Tavern için ultimate custom client screen, packet tabanlı UI, texture destekli, WAL recovery taramalı ve transaction güvenlikli medieval RPG pazar/açık artırma sistemi.
Bu sürüm özel client ekranı kullandığı için hem server hem client tarafına kurulmalıdır.
'''

[[dependencies.ruasolmarket]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ruasolmarket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
